config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  get '/top', to: 'home#top'
  # get 'home/top'

  # get 'cart/index'
  # get 'cart/create'

  # get 'charges/new'
  # get 'charges/create'

  resources :items
  resources :cart
  resources :charges, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
	mount_uploader :image, ItemImageUploader
# ここ書いた後でサーバー再起動しないと、エラーになる

	validates :name, presence: true
	validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :timeoutable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_admin!

  before_action :configure_permitted_parameters, if: :devise_controller?

private
	def configure_permitted_parameters
		# オリジナルカラムの登録を許可
		devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
		# オリジナルカラムの変更を許可
		devise_parameter_sanitizer.permit(:account_update, keys: [:username])
	end

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def index
    # @items = []
    # (session[:cart] || []).each do |item_id|
    #   @items << Item.find(item_id)
    # end
    @items = (session[:cart] || []).map { |item_id| Item.find(item_id) }
    # binding.pry
    @sum = (@items.map{|item| item.price}).sum
    # binding.pry
  end

  def create
    # セッションに値を保存する
    # sessionを空の配列とし、もしsession[:cart]が存在してたら、これを作らない（データがなくなってまう）
    session[:cart] = [] unless session[:cart]
    session[:cart] << params[:item_id]
    redirect_to top_path
  end

  def update
    # 一つだけ商品を削除
    @items = session[:cart].delete_at(session[:cart].find_index(params[:id]))
    # binding.pry
    redirect_to cart_index_path
  end

  def destroy
    session[:cart] = []
    # カートの中身を削除してから、改めてカート変数を作成するために、indexアクションへ飛ばす（または、カートページにてカートの中身を判定するためとも言える）
    redirect_to action: 'index'
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    amount = 0
    (session[:cart] || []).each do |item_id|
      # amount = amount + Item.find(item_id).price　ということです
      amount += Item.find(item_id).price
    end
    # 以下のコードの意味
    customer = Stripe::Customer.create(
      email: params[:stripeEmail],
      source: params[:stripeToken]
      )
    Stripe::Charge.create(
      customer: customer.id,
      amount: amount,
      currency: 'jpy'
      )
    # 決済が終わったら、セッションカートを空にする
    session[:cart] = []
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	before_action :authenticate_user!, only: :top

  def top
  	@items = Item.all.reverse
  end

  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  layout 'items_application'

  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :price, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/cart/create.html.erb
<h1>Cart#create</h1>
<p>Find me in app/views/cart/create.html.erb</p>

app/views/cart/index.html.erb
<h1>カートの中身</h1>

<!--以下を課題に-->
<% @items.each do |item| %>
    <p>
        商品名: <%= item.name %>、　 価格: <%= item.price %>円
        <%= link_to '[x]', cart_path(item), method: :patch, class: 'command', data: { confirm: '本当に？' } %>
    </p>
<% end %>

<% if @items != [] %>
	<%= form_tag('/cart/:id', :method => :delete) do %>
	    <%= submit_tag 'カートを空にする' %>
	<% end %>
<% end -%>
<br><br>

<!-- 以降は、決済コンポーネントなので、決済機能追加後 -->
<!--mapとeachの違いは、処理はほぼ同じでも、mapは新しい配列にして返す-->
<!-- <% sum = (@items.map{|item| item.price}).sum %> -->
<%= form_tag charges_path do %>
    <article>
        <% if flash[:error].present? %>
            <div id="error_explanation" >
                <p><%= flash[:error] %></p>
            </div>
        <% end %>
        <label class="amount">
            <span>合計金額: <%= @sum %>円</span>
        </label>
    </article>

    <% if @items != [] %>
    <!--↓は、こういうものです。-->
	    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button" 
	            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
	            data-description='商品のご購入'
	            data-amount="<%= @sum %>"
	            data-currency="jpy"
	            data-locale="auto"></script>
	<% end -%>
<% end %>

<br><br>
<%= link_to '買い物を続ける', top_path %>

app/views/charges/create.html.erb
<h1>お支払い完了ページ</h1>
<p>ありがとうございました</p>

<!-- ブラウザの戻るボタンを無効に -->
<script type="text/javascript">
    // (function(){
    //     window.location.hash="no-back";
    //     window.location.hash="no-back-button";
    //     window.onhashchange=function(){
    //         window.location.hash="no-back";
    //     }
    // })();
    // var test = function(){
    //     alert('てすと');
    // }
    // test();

    // history.pushState(null, null, null);

    // window.addEventListener("popstate", function() {
    //     history.pushState(null, null, null);
    // });
	// window.location.hash="#noback";
	// window.onhashchange=function(){
	//     window.location.hash="#noback";
	// }

// window.onunload = function(){};
// history.forward();

</script>

app/views/charges/new.html.erb
<h1>Charges#new</h1>
<p>Find me in app/views/charges/new.html.erb</p>

app/views/home/index.html.erb
<h1>ようこそECサイトへ</h1>
<% if current_user %>
	<%= link_to '買い物をする', top_path %>
<% else %>
	<p>サインアップもしくはログインしてください</p>
<% end -%>

app/views/home/top.html.erb
<h1>商品一覧</h1>

<% @items.each do |item| %>
<div class="item">
	<tr>
		<th>
			<%= item.name %> : <%= item.price %>
			<br>
			<!-- width指定しな場合は、アップロードした時の設定サイズとなる -->
			<%= image_tag item.image, width:'100' %>
		</th>
	    <!--ここで cartパスを指定することでcartコントローラーに飛ぶ-->
	    <%= form_tag '/cart' do %>
	        <%= hidden_field_tag :item_id, item.id %>
	        <%= submit_tag 'カートに入れる', class: 'in_cart' %>
	    <% end %>
	</tr>
</div>
<% end -%>
<div class="space-s"></div>

<%= link_to 'カートを見る', '/cart' %>
<div class="space-m"></div>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :item_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :item_description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :item_price %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :item_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.description %></td>
        <td><%= item.price %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Image:</strong>
  <!-- サイズ指定しないとアップロードした時の設定サイズで表示 -->
  <%= image_tag @item.image %>
  <!-- <%= image_tag @item.image, width:'100' %> -->

</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcSite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrap">
  	<!-- headerはdeviseを追加したことによる -->
    <header>
        <nav>
            <% if user_signed_in? %>
            	<h2><%= current_user.username %>さん またお会いしましたね</h2>
	            <%= link_to 'プロフィール変更', edit_user_registration_path %>
	            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
	          <% else %>
	            <%= link_to 'サインアップ', new_user_registration_path %>
	            <%= link_to 'ログイン', new_user_session_path %>
            <% end %>
        </nav>
    </header>

  	<!-- devise用flash -->
  	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/items_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcSite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>